#!/usr/bin/env bash

set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 2 )) && {
   syntax_error "$0 <file> <pattern>"
}

FILE="$1" PATTERN="$2"

[[ ! -f "$FILE" ]] && {
   syntax_error "file not found: $FILE"
}


if ! grep "${PATTERN}" "$FILE"
then
	echo "Pattern '$PATTERN' not found in '$FILE'."
    exit 1
fi

# Done. Exit with last command exit status.
exit $?

