#!/usr/bin/env bash

set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 1 )) && {
   syntax_error "$0 <file>"
}

FILE=$1

if [[ -f "$FILE" ]]
then
	echo "File exists: $FILE"
else
	echo "File does not exist: $FILE"	
	exit 1
fi	

# Done. Exit with last command exit status.
exit $?

