name: nixy-local-steps
rundeckPluginVersion: 1.2
author: "@author@"
date: "@date@"
version: "@version@"
url: "@url@"
description: Step plugins for *nix rundeck server
rundeckCompatibilityVersion: 3.x
targetHostCompatibility: unix
license: Apache 2.0
tags:
  - script
  - WorkflowStep
providers:
  - name: nixy-local-workflow-step
    service: WorkflowStep
    title: '*nixy / local-script'
    description: 'Run an inline script locally once for the workflow'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: local-script
    script-args: ${config.arguments}
    config:
      - type: String
        name: script
        title: script
        description: "the shell script"
        required: true        
        renderingOptions:
          displayType: CODE
          codeSyntaxMode: SH
      - type: String
        name: arguments
        title: Arguments
        description: "optional command line arguments"
        required: false   
  - name: nixy-local-node-step
    service: WorkflowNodeStep
    title: '*nixy / local-script'
    description: 'Run an inline script locally for each node'
    plugin-type: script
    script-interpreter: /usr/bin/env bash
    script-file: local-script
    script-args: ${config.arguments}
    config:
      - type: String
        name: script
        title: script
        description: "the shell script"
        required: true        
        renderingOptions:
          displayType: CODE
          codeSyntaxMode: SH
      - type: String
        name: arguments
        title: Arguments
        description: "optional command line arguments"
        required: false   
