#!/usr/bin/env bash

set -eu

[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx

syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# < 1 )) && {
   syntax_error "$0 <arguments>"
}

# Read script arguments
declare -ar ARGUMENTS=("$@")

[[ -z "${RD_CONFIG_SCRIPT:-}" ]] && {
   syntax_error "RD_CONFIG_SCRIPT environment variable unset."
}

if [ -z "${RD_CONFIG_TMP:-}" ]; then
   scriptfile=$(mktemp -t "script.$RD_JOB_EXECID.XXXXXX")
else
   tmp_folder="${RD_CONFIG_TMP:-}"
   mkdir -p "$tmp_folder"
   scriptfile=$(mktemp "$tmp_folder/script.$RD_JOB_EXECID.XXXXXX")
fi

# Write user defined script code to temp file.
cat > "$scriptfile" <<< "$RD_CONFIG_SCRIPT"
trap 'rm "$scriptfile"' EXIT; # clean up on exit.


# Make the script executable and then run it.
chmod +x "$scriptfile"
"$scriptfile" ${ARGUMENTS[@]}
exit $?
# Done.
