#!/usr/bin/env bash


set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 4 )) && {
   syntax_error "$0 <file> <pattern> <interval> <maxtries>"
}


FILE=$1 PATTERN=$2 INTERVAL=$3 MAXTRY=$4

[[ ! -f "$FILE" ]] && {
   syntax_error "file not found: $FILE"
}

progress_tic() { [[ -t 1 ]] && { printf -- "%s" "$*"; } || { printf -- "%s\n" "$*"; } }

declare -i attempts=0 

# Keep checking for pattern until we reach maxtry attempts.
while (( attempts <= $MAXTRY ))
do
    if ! grep "${PATTERN}" "$FILE"
    then  
        # output a progress string.
        progress_tic "."; 
    else  
        # Success. Found the string in file.
        break; 
    fi
    # increment attempts attemptser.
    (( attempts += 1 ))

    # error out if reached max attempts.
    (( attempts == MAXTRY )) && {
        echo "FAIL: Reached max attempts to find string in $FILE. Exiting."
        exit 1
    }
    # wait interval before trying again.
    sleep "$INTERVAL"
done

# Done. Exit with last command exit status.
exit $?

