#!/usr/bin/env bash

set -eu

[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }


(( $# != 3 )) && {
   syntax_error "$0 <url> <interval> <maxtry>"
}

declare -r URL=$1

curl_output=$(curl -L -o /dev/null --head --write-out '%{http_code}\n' "$URL" 2>&1)
curl_exit=$?

if [ $curl_exit -ne 0 ]; then
	# got an error
	echo "NOT_READY: $URL"
	[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && printf >&2 "DEBUG: Curl error (exit $curl_exit): %s\n" "$curl_output"
	exit 1
fi

status_code=$(echo "$curl_output" | tail -1)

case "${status_code}" in
	[2-3]0[0-9])
		echo "OK: $URL"
	;;
	40[0-9]) 
		echo "NOT_ALLOWED ($status_code): $URL"
	;;
	5[0-9][0-9]) 	
	echo "NOT_HEALTHY ($status_code): $URL"
	exit 3
esac

# Done. Exit with last command exit status.
exit $?

