#!/usr/bin/env bash

set -eu

[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }


(( $# != 3 )) && {
   syntax_error "$0 <url> <interval> <maxtry>"
}

URL=$1 INTERVAL=$2 MAXTRY=$3


if ! status_code=$(curl -L -o /dev/null --silent --head --write-out '%{http_code}\n' $URL)
then
	# got an error
	echo "NOT_READY: $URL"
	exit 1
fi

case "${status_code}" in
	[2-3]0[0-9])
		echo "OK: $URL"
	;;
	40[0-9]) 
		echo "NOT_ALLOWED ($status_code): $URL"
	;;
	5[0-9][0-9]) 	
	echo "NOT_HEALTHY ($status_code): $URL"
	exit 3
esac

# Done. Exit with last command exit status.
exit $?

