#!/usr/bin/env bash

set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 3 )) && {
   syntax_error "$0 <host> <interval> <maxtry>"
}

declare -r HOST=$1 INTERVAL=$2 MAXTRY=$3

progress_tic() { if [[ -t 1 ]]; then printf -- "%s" "$@"; else printf -- "%s\n" "$@" ;  fi ; }

declare -i attempts=0

until ( ping_output=$(ping -c 1 "$HOST" 2>&1); echo "$ping_output" | grep -q ^64 )
do
   sleep "$INTERVAL"
   progress_tic .

   (( attempts += 1 ))  ; # increment counter for the failed attempt.
   (( attempts == MAXTRY )) && {
        printf >&2 "\nReached max tries: $attempts. Could not ping to host %s. Exiting.\n" "$HOST"
        [[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && printf >&2 "DEBUG: Last ping output: %s\n" "$ping_output"
        exit 1
   }
   [[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && printf >&2 "DEBUG: Ping attempt $attempts failed: %s\n" "$ping_output"
done

echo "OK: $HOST is pingable."

#
exit $?
