#!/usr/bin/env bash

set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 2 )) && {
   syntax_error "$0 <host> <interval>"
}

declare -r HOST=$1 INTERVAL=$2

progress_tic() { if [[ -t 1 ]]; then printf -- "%s" "$@"; else printf -- "%s\n" "$@" ;  fi ; }

until ( ping -c 1 "$HOST" | grep -q ^64 )
do
   sleep "$INTERVAL"
   progress_tic .
done

echo "OK: $HOST is pingable."

#
exit $?
