#!/usr/bin/env bash

set -eu
[[ "${RD_JOB_LOGLEVEL:-}" == "DEBUG" ]] && set -vx
syntax_error() { echo >&2 "SYNTAX: $*"; exit 2; }

(( $# != 1 )) && {
   syntax_error "$0 <interval>"
}

declare -r INTERVAL=$1

[[ "$INTERVAL" =~ [0-9]+ ]] || {
    syntax_error 'interval must be an interger.'
}

echo "sleeping $INTERVAL ..."
sleep "$INTERVAL"

echo "OK: sleep complete."

# Done. Exit with last command exit status.
exit $?

