name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Fetch Tags
      run: git -c protocol.version=2 fetch --tags --progress --no-recurse-submodules origin
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Release Version
      id: get_version
      run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo ::set-output name=VERSION::$VERSION
    - name: Upload command plugin zip
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: command-${{ steps.get_version.outputs.VERSION }}
        # Directory containing files to upload
        path: ./command/build/libs/command-v${{ steps.get_version.outputs.VERSION }}.zip
    - name: Upload file plugin zip
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: file-${{ steps.get_version.outputs.VERSION }}
        # Directory containing files to upload
        path: ./file/build/libs/file-v${{ steps.get_version.outputs.VERSION }}.zip
    - name: Upload local-script plugin zip
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: local-script-${{ steps.get_version.outputs.VERSION }}
        # Directory containing files to upload
        path: ./local-script/build/libs/local-script-v${{ steps.get_version.outputs.VERSION }}.zip
    - name: Upload waitfor plugin zip
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: waitfor-${{ steps.get_version.outputs.VERSION }}
        # Directory containing files to upload
        path: ./waitfor/build/libs/waitfor-v${{ steps.get_version.outputs.VERSION }}.zip