name: Java CI

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true

    - name: Build with Gradle
      run: ./gradlew build --parallel

    - name: Get Release Version
      id: get_version
      run: |
        VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Upload command plugin zip
      uses: actions/upload-artifact@v4
      with:
        name: command-${{ steps.get_version.outputs.VERSION }}
        path: ./command/build/libs/command-v${{ steps.get_version.outputs.VERSION }}.zip
        if-no-files-found: error

    - name: Upload file plugin zip
      uses: actions/upload-artifact@v4
      with:
        name: file-${{ steps.get_version.outputs.VERSION }}
        path: ./file/build/libs/file-v${{ steps.get_version.outputs.VERSION }}.zip
        if-no-files-found: error

    - name: Upload local-script plugin zip
      uses: actions/upload-artifact@v4
      with:
        name: local-script-${{ steps.get_version.outputs.VERSION }}
        path: ./local-script/build/libs/local-script-v${{ steps.get_version.outputs.VERSION }}.zip
        if-no-files-found: error

    - name: Upload waitfor plugin zip
      uses: actions/upload-artifact@v4
      with:
        name: waitfor-${{ steps.get_version.outputs.VERSION }}
        path: ./waitfor/build/libs/waitfor-v${{ steps.get_version.outputs.VERSION }}.zip
        if-no-files-found: error