on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Release Version
        id: get_version
        run: |
          VERSION=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./command/build/libs/command-v${{ env.VERSION }}.zip
            ./file/build/libs/file-v${{ env.VERSION }}.zip
            ./local-script/build/libs/local-script-v${{ env.VERSION }}.zip
            ./waitfor/build/libs/waitfor-v${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}