on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get Release Version
        id: get_version
        run: VERSION=$(./gradlew currentVersion -q -Prelease.quiet) && echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Release and Upload Assets
        id: create_release
        run: |
          gh release create \
            --generate-notes \
            --title 'Release ${{ steps.get_version.outputs.VERSION }}' \
            ${{ github.ref_name }} \
            ./command/build/libs/command-v${{ steps.get_version.outputs.VERSION }}.zip#command-${{ steps.get_version.outputs.VERSION }}.zip \
            ./file/build/libs/file-v${{ steps.get_version.outputs.VERSION }}.zip#file-${{ steps.get_version.outputs.VERSION }}.zip \
            ./local-script/build/libs/local-script-v${{ steps.get_version.outputs.VERSION }}.zip#local-script-${{ steps.get_version.outputs.VERSION }}.zip \
            ./waitfor/build/libs/waitfor-v${{ steps.get_version.outputs.VERSION }}.zip#waitfor-${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
